// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "dijkstra.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dijkstra::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dijkstra::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<26> dijkstra::ap_ST_st1_fsm_0 = "1";
const sc_lv<26> dijkstra::ap_ST_st2_fsm_1 = "10";
const sc_lv<26> dijkstra::ap_ST_st3_fsm_2 = "100";
const sc_lv<26> dijkstra::ap_ST_st4_fsm_3 = "1000";
const sc_lv<26> dijkstra::ap_ST_st5_fsm_4 = "10000";
const sc_lv<26> dijkstra::ap_ST_st6_fsm_5 = "100000";
const sc_lv<26> dijkstra::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<26> dijkstra::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<26> dijkstra::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<26> dijkstra::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<26> dijkstra::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<26> dijkstra::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<26> dijkstra::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<26> dijkstra::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<26> dijkstra::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<26> dijkstra::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<26> dijkstra::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<26> dijkstra::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<26> dijkstra::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<26> dijkstra::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<32> dijkstra::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dijkstra::ap_const_lv1_1 = "1";
const sc_lv<32> dijkstra::ap_const_lv32_1 = "1";
const sc_lv<32> dijkstra::ap_const_lv32_2 = "10";
const sc_lv<1> dijkstra::ap_const_lv1_0 = "0";
const sc_lv<32> dijkstra::ap_const_lv32_3 = "11";
const sc_lv<32> dijkstra::ap_const_lv32_6 = "110";
const sc_lv<32> dijkstra::ap_const_lv32_7 = "111";
const sc_lv<32> dijkstra::ap_const_lv32_8 = "1000";
const sc_lv<32> dijkstra::ap_const_lv32_9 = "1001";
const sc_lv<32> dijkstra::ap_const_lv32_A = "1010";
const sc_lv<32> dijkstra::ap_const_lv32_B = "1011";
const sc_lv<32> dijkstra::ap_const_lv32_C = "1100";
const sc_lv<32> dijkstra::ap_const_lv32_E = "1110";
const sc_lv<32> dijkstra::ap_const_lv32_F = "1111";
const sc_lv<32> dijkstra::ap_const_lv32_10 = "10000";
const sc_lv<32> dijkstra::ap_const_lv32_12 = "10010";
const sc_lv<32> dijkstra::ap_const_lv32_13 = "10011";
const sc_lv<32> dijkstra::ap_const_lv32_14 = "10100";
const sc_lv<32> dijkstra::ap_const_lv32_16 = "10110";
const sc_lv<32> dijkstra::ap_const_lv32_17 = "10111";
const sc_lv<32> dijkstra::ap_const_lv32_18 = "11000";
const sc_lv<4> dijkstra::ap_const_lv4_0 = "0000";
const sc_lv<32> dijkstra::ap_const_lv32_4 = "100";
const sc_lv<32> dijkstra::ap_const_lv32_5 = "101";
const sc_lv<32> dijkstra::ap_const_lv32_D = "1101";
const sc_lv<8> dijkstra::ap_const_lv8_FF = "11111111";
const sc_lv<32> dijkstra::ap_const_lv32_11 = "10001";
const sc_lv<32> dijkstra::ap_const_lv32_15 = "10101";
const sc_lv<4> dijkstra::ap_const_lv4_1 = "1";
const sc_lv<32> dijkstra::ap_const_lv32_19 = "11001";
const sc_lv<4> dijkstra::ap_const_lv4_8 = "1000";
const sc_lv<3> dijkstra::ap_const_lv3_0 = "000";
const sc_lv<8> dijkstra::ap_const_lv8_0 = "00000000";
const sc_lv<4> dijkstra::ap_const_lv4_6 = "110";
const sc_lv<6> dijkstra::ap_const_lv6_0 = "000000";

dijkstra::dijkstra(sc_module_name name) : sc_module(name), mVcdFile(0) {
    vector_U = new dijkstra_vector("vector_U");
    vector_U->clk(ap_clk);
    vector_U->reset(ap_rst);
    vector_U->address0(vector_address0);
    vector_U->ce0(vector_ce0);
    vector_U->we0(vector_we0);
    vector_U->d0(vector_d0);
    vector_U->q0(vector_q0);
    matrix_U = new dijkstra_matrix("matrix_U");
    matrix_U->clk(ap_clk);
    matrix_U->reset(ap_rst);
    matrix_U->address0(matrix_address0);
    matrix_U->ce0(matrix_ce0);
    matrix_U->we0(matrix_we0);
    matrix_U->d0(matrix_d0);
    matrix_U->q0(matrix_q0);
    result_U = new dijkstra_result("result_U");
    result_U->clk(ap_clk);
    result_U->reset(ap_rst);
    result_U->address0(result_address0);
    result_U->ce0(result_ce0);
    result_U->we0(result_we0);
    result_U->d0(result_d0);
    result_U->q0(result_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( exitcond_fu_830_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( exitcond_fu_830_p2 );

    SC_METHOD(thread_ap_sig_bdd_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_129);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_146);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_162);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_175);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_189);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_201);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_215);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_225);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_239);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_248);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_261);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_273);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_291);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_304);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_316);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_334);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_347);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_359);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_390);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_399);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_417);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_447);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_463);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_477);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_201 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_215 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_225 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_239 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_417 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_248 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_261 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_273 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_447 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_291 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_42 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_304 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_316 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_bdd_463 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_334 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_bdd_347 );

    SC_METHOD(thread_ap_sig_cseq_ST_st25_fsm_24);
    sensitive << ( ap_sig_bdd_359 );

    SC_METHOD(thread_ap_sig_cseq_ST_st26_fsm_25);
    sensitive << ( ap_sig_bdd_477 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_120 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_129 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_146 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_390 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_399 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_162 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_175 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_189 );

    SC_METHOD(thread_e_5_fu_519_p2);
    sensitive << ( e_reg_290 );

    SC_METHOD(thread_e_6_fu_579_p2);
    sensitive << ( e_1_reg_313 );

    SC_METHOD(thread_e_7_fu_642_p2);
    sensitive << ( e_2_reg_348 );

    SC_METHOD(thread_e_8_fu_711_p2);
    sensitive << ( e_3_reg_395 );

    SC_METHOD(thread_e_9_fu_773_p2);
    sensitive << ( e_4_reg_419 );

    SC_METHOD(thread_exitcond10_fu_705_p2);
    sensitive << ( vector_load_2_reg_986 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( e_3_reg_395 );

    SC_METHOD(thread_exitcond11_fu_767_p2);
    sensitive << ( vector_load_3_reg_1021 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( e_4_reg_419 );

    SC_METHOD(thread_exitcond1_fu_460_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_exitcond2_fu_477_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_1_reg_279 );

    SC_METHOD(thread_exitcond3_fu_513_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( e_reg_290 );

    SC_METHOD(thread_exitcond4_fu_552_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( i_2_reg_301 );

    SC_METHOD(thread_exitcond5_fu_607_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( i_3_reg_324 );

    SC_METHOD(thread_exitcond6_fu_573_p2);
    sensitive << ( vector_load_reg_917 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( e_1_reg_313 );

    SC_METHOD(thread_exitcond7_fu_676_p2);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( i_4_reg_383 );

    SC_METHOD(thread_exitcond8_fu_636_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( e_2_reg_348 );

    SC_METHOD(thread_exitcond9_fu_738_p2);
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( i_5_reg_406 );

    SC_METHOD(thread_exitcond_fu_830_p2);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( i_7_reg_443 );

    SC_METHOD(thread_i_10_fu_613_p2);
    sensitive << ( i_3_reg_324 );

    SC_METHOD(thread_i_11_fu_682_p2);
    sensitive << ( i_4_reg_383 );

    SC_METHOD(thread_i_12_fu_744_p2);
    sensitive << ( i_5_reg_406 );

    SC_METHOD(thread_i_14_fu_558_p2);
    sensitive << ( i_2_reg_301 );

    SC_METHOD(thread_i_16_fu_818_p2);
    sensitive << ( i_6_reg_431 );

    SC_METHOD(thread_i_17_fu_836_p2);
    sensitive << ( i_7_reg_443 );

    SC_METHOD(thread_i_8_fu_466_p2);
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_i_9_fu_483_p2);
    sensitive << ( i_1_reg_279 );

    SC_METHOD(thread_in_data_V_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_9_fu_534_p1 );

    SC_METHOD(thread_in_data_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_in_last_V_address0);

    SC_METHOD(thread_in_last_V_address1);

    SC_METHOD(thread_in_last_V_ce0);

    SC_METHOD(thread_in_last_V_ce1);

    SC_METHOD(thread_in_last_V_d0);

    SC_METHOD(thread_in_last_V_d1);

    SC_METHOD(thread_in_last_V_we0);

    SC_METHOD(thread_in_last_V_we1);

    SC_METHOD(thread_matrix_addr1_cast_fu_763_p1);
    sensitive << ( tmp_29_fu_755_p3 );

    SC_METHOD(thread_matrix_addr1_fu_543_p2);
    sensitive << ( matrix_addr9_cast_reg_881 );
    sensitive << ( tmp_trn_cast_fu_539_p1 );

    SC_METHOD(thread_matrix_addr2_fu_783_p2);
    sensitive << ( matrix_addr1_cast_reg_1025 );
    sensitive << ( tmp_24_trn_cast_fu_779_p1 );

    SC_METHOD(thread_matrix_addr3_cast_fu_701_p1);
    sensitive << ( tmp_26_fu_693_p3 );

    SC_METHOD(thread_matrix_addr4_fu_721_p2);
    sensitive << ( matrix_addr3_cast_reg_990 );
    sensitive << ( tmp_20_trn_cast_fu_717_p1 );

    SC_METHOD(thread_matrix_addr5_cast_fu_632_p1);
    sensitive << ( tmp_18_fu_624_p3 );

    SC_METHOD(thread_matrix_addr6_fu_652_p2);
    sensitive << ( matrix_addr5_cast_reg_950 );
    sensitive << ( tmp_15_trn_cast_fu_648_p1 );

    SC_METHOD(thread_matrix_addr7_cast_fu_593_p1);
    sensitive << ( tmp_27_fu_585_p3 );

    SC_METHOD(thread_matrix_addr8_fu_597_p2);
    sensitive << ( tmp_2_trn_cast_reg_921 );
    sensitive << ( matrix_addr7_cast_fu_593_p1 );

    SC_METHOD(thread_matrix_addr9_cast_fu_509_p1);
    sensitive << ( tmp_12_fu_501_p3 );

    SC_METHOD(thread_matrix_address0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( matrix_addr_3_reg_1003 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( tmp_15_fu_548_p1 );
    sensitive << ( tmp_28_fu_602_p1 );
    sensitive << ( tmp_30_fu_657_p1 );
    sensitive << ( tmp_31_fu_726_p1 );
    sensitive << ( tmp_32_fu_788_p1 );

    SC_METHOD(thread_matrix_ce0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_matrix_d0);
    sensitive << ( in_data_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( tmp_19_fu_731_p2 );

    SC_METHOD(thread_matrix_we0);
    sensitive << ( vector_load_reg_917 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( exitcond6_fu_573_p2 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_min_4_min_1_fu_668_p3);
    sensitive << ( matrix_q0 );
    sensitive << ( min_1_reg_359 );
    sensitive << ( tmp_14_fu_662_p2 );

    SC_METHOD(thread_out_data_V_address0);
    sensitive << ( tmp_25_reg_1074 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );

    SC_METHOD(thread_out_data_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );

    SC_METHOD(thread_out_data_V_d0);
    sensitive << ( result_q0 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );

    SC_METHOD(thread_out_data_V_we0);
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );

    SC_METHOD(thread_out_last_V_address0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( tmp_25_fu_842_p1 );

    SC_METHOD(thread_out_last_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_out_last_V_d0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( i_7_reg_443 );

    SC_METHOD(thread_out_last_V_we0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( exitcond_fu_830_p2 );

    SC_METHOD(thread_result_address0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( tmp_25_fu_842_p1 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_23_fu_793_p1 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_result_d0);
    sensitive << ( i_5_reg_406 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_result_we0);
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_24_fu_799_p2 );

    SC_METHOD(thread_tmp_10_fu_619_p1);
    sensitive << ( i_3_reg_324 );

    SC_METHOD(thread_tmp_12_fu_501_p3);
    sensitive << ( i_1_reg_279 );

    SC_METHOD(thread_tmp_13_fu_688_p1);
    sensitive << ( i_4_reg_383 );

    SC_METHOD(thread_tmp_14_fu_662_p2);
    sensitive << ( matrix_q0 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( min_1_reg_359 );

    SC_METHOD(thread_tmp_15_fu_548_p1);
    sensitive << ( matrix_addr1_reg_899 );

    SC_METHOD(thread_tmp_15_trn_cast_fu_648_p1);
    sensitive << ( e_2_reg_348 );

    SC_METHOD(thread_tmp_17_fu_750_p1);
    sensitive << ( i_5_reg_406 );

    SC_METHOD(thread_tmp_18_fu_624_p3);
    sensitive << ( i_3_reg_324 );

    SC_METHOD(thread_tmp_19_fu_731_p2);
    sensitive << ( matrix_q0 );
    sensitive << ( min_reg_336 );

    SC_METHOD(thread_tmp_1_fu_472_p1);
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_tmp_20_trn_cast_fu_717_p1);
    sensitive << ( e_3_reg_395 );

    SC_METHOD(thread_tmp_21_fu_813_p1);
    sensitive << ( i_6_reg_431 );

    SC_METHOD(thread_tmp_22_fu_824_p2);
    sensitive << ( vector_q0 );
    sensitive << ( tmp_20_reg_1046 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( i_6_reg_431 );

    SC_METHOD(thread_tmp_23_fu_793_p1);
    sensitive << ( e_4_reg_419 );

    SC_METHOD(thread_tmp_24_fu_799_p2);
    sensitive << ( matrix_q0 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_tmp_24_trn_cast_fu_779_p1);
    sensitive << ( e_4_reg_419 );

    SC_METHOD(thread_tmp_25_fu_842_p1);
    sensitive << ( i_7_reg_443 );

    SC_METHOD(thread_tmp_26_fu_693_p3);
    sensitive << ( i_4_reg_383 );

    SC_METHOD(thread_tmp_27_fu_585_p3);
    sensitive << ( e_1_reg_313 );

    SC_METHOD(thread_tmp_28_fu_602_p1);
    sensitive << ( matrix_addr8_fu_597_p2 );

    SC_METHOD(thread_tmp_29_fu_755_p3);
    sensitive << ( i_5_reg_406 );

    SC_METHOD(thread_tmp_2_fu_564_p1);
    sensitive << ( i_2_reg_301 );

    SC_METHOD(thread_tmp_2_trn_cast_fu_569_p1);
    sensitive << ( i_2_reg_301 );

    SC_METHOD(thread_tmp_30_fu_657_p1);
    sensitive << ( matrix_addr6_fu_652_p2 );

    SC_METHOD(thread_tmp_31_fu_726_p1);
    sensitive << ( matrix_addr4_fu_721_p2 );

    SC_METHOD(thread_tmp_32_fu_788_p1);
    sensitive << ( matrix_addr2_fu_783_p2 );

    SC_METHOD(thread_tmp_4_fu_493_p3);
    sensitive << ( tmp_5_fu_489_p1 );

    SC_METHOD(thread_tmp_5_fu_489_p1);
    sensitive << ( i_1_reg_279 );

    SC_METHOD(thread_tmp_7_cast_fu_525_p1);
    sensitive << ( e_reg_290 );

    SC_METHOD(thread_tmp_8_fu_529_p2);
    sensitive << ( tmp_4_reg_876 );
    sensitive << ( tmp_7_cast_fu_525_p1 );

    SC_METHOD(thread_tmp_9_fu_534_p1);
    sensitive << ( tmp_8_fu_529_p2 );

    SC_METHOD(thread_tmp_fu_455_p1);
    sensitive << ( start_point_V );

    SC_METHOD(thread_tmp_trn_cast_fu_539_p1);
    sensitive << ( e_reg_290 );

    SC_METHOD(thread_vector_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_fu_455_p1 );
    sensitive << ( tmp_1_fu_472_p1 );
    sensitive << ( tmp_2_fu_564_p1 );
    sensitive << ( tmp_10_fu_619_p1 );
    sensitive << ( tmp_13_fu_688_p1 );
    sensitive << ( tmp_17_fu_750_p1 );
    sensitive << ( tmp_23_fu_793_p1 );
    sensitive << ( tmp_21_fu_813_p1 );

    SC_METHOD(thread_vector_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_vector_d0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_vector_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_460_p2 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_24_fu_799_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( vector_q0 );
    sensitive << ( exitcond2_fu_477_p2 );
    sensitive << ( exitcond3_fu_513_p2 );
    sensitive << ( exitcond4_fu_552_p2 );
    sensitive << ( vector_load_reg_917 );
    sensitive << ( exitcond5_fu_607_p2 );
    sensitive << ( exitcond8_fu_636_p2 );
    sensitive << ( exitcond7_fu_676_p2 );
    sensitive << ( vector_load_2_reg_986 );
    sensitive << ( exitcond10_fu_705_p2 );
    sensitive << ( exitcond9_fu_738_p2 );
    sensitive << ( vector_load_3_reg_1021 );
    sensitive << ( exitcond11_fu_767_p2 );
    sensitive << ( tmp_20_reg_1046 );
    sensitive << ( exitcond_fu_830_p2 );
    sensitive << ( exitcond1_fu_460_p2 );
    sensitive << ( exitcond6_fu_573_p2 );
    sensitive << ( tmp_22_fu_824_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dijkstra_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_data_V_address0, "(port)in_data_V_address0");
    sc_trace(mVcdFile, in_data_V_ce0, "(port)in_data_V_ce0");
    sc_trace(mVcdFile, in_data_V_q0, "(port)in_data_V_q0");
    sc_trace(mVcdFile, in_last_V_address0, "(port)in_last_V_address0");
    sc_trace(mVcdFile, in_last_V_ce0, "(port)in_last_V_ce0");
    sc_trace(mVcdFile, in_last_V_we0, "(port)in_last_V_we0");
    sc_trace(mVcdFile, in_last_V_d0, "(port)in_last_V_d0");
    sc_trace(mVcdFile, in_last_V_q0, "(port)in_last_V_q0");
    sc_trace(mVcdFile, in_last_V_address1, "(port)in_last_V_address1");
    sc_trace(mVcdFile, in_last_V_ce1, "(port)in_last_V_ce1");
    sc_trace(mVcdFile, in_last_V_we1, "(port)in_last_V_we1");
    sc_trace(mVcdFile, in_last_V_d1, "(port)in_last_V_d1");
    sc_trace(mVcdFile, in_last_V_q1, "(port)in_last_V_q1");
    sc_trace(mVcdFile, start_point_V, "(port)start_point_V");
    sc_trace(mVcdFile, out_data_V_address0, "(port)out_data_V_address0");
    sc_trace(mVcdFile, out_data_V_ce0, "(port)out_data_V_ce0");
    sc_trace(mVcdFile, out_data_V_we0, "(port)out_data_V_we0");
    sc_trace(mVcdFile, out_data_V_d0, "(port)out_data_V_d0");
    sc_trace(mVcdFile, out_last_V_address0, "(port)out_last_V_address0");
    sc_trace(mVcdFile, out_last_V_ce0, "(port)out_last_V_ce0");
    sc_trace(mVcdFile, out_last_V_we0, "(port)out_last_V_we0");
    sc_trace(mVcdFile, out_last_V_d0, "(port)out_last_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_42, "ap_sig_bdd_42");
    sc_trace(mVcdFile, vector_address0, "vector_address0");
    sc_trace(mVcdFile, vector_ce0, "vector_ce0");
    sc_trace(mVcdFile, vector_we0, "vector_we0");
    sc_trace(mVcdFile, vector_d0, "vector_d0");
    sc_trace(mVcdFile, vector_q0, "vector_q0");
    sc_trace(mVcdFile, matrix_address0, "matrix_address0");
    sc_trace(mVcdFile, matrix_ce0, "matrix_ce0");
    sc_trace(mVcdFile, matrix_we0, "matrix_we0");
    sc_trace(mVcdFile, matrix_d0, "matrix_d0");
    sc_trace(mVcdFile, matrix_q0, "matrix_q0");
    sc_trace(mVcdFile, result_address0, "result_address0");
    sc_trace(mVcdFile, result_ce0, "result_ce0");
    sc_trace(mVcdFile, result_we0, "result_we0");
    sc_trace(mVcdFile, result_d0, "result_d0");
    sc_trace(mVcdFile, result_q0, "result_q0");
    sc_trace(mVcdFile, i_8_fu_466_p2, "i_8_fu_466_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_120, "ap_sig_bdd_120");
    sc_trace(mVcdFile, i_9_fu_483_p2, "i_9_fu_483_p2");
    sc_trace(mVcdFile, i_9_reg_871, "i_9_reg_871");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_129, "ap_sig_bdd_129");
    sc_trace(mVcdFile, tmp_4_fu_493_p3, "tmp_4_fu_493_p3");
    sc_trace(mVcdFile, tmp_4_reg_876, "tmp_4_reg_876");
    sc_trace(mVcdFile, exitcond2_fu_477_p2, "exitcond2_fu_477_p2");
    sc_trace(mVcdFile, matrix_addr9_cast_fu_509_p1, "matrix_addr9_cast_fu_509_p1");
    sc_trace(mVcdFile, matrix_addr9_cast_reg_881, "matrix_addr9_cast_reg_881");
    sc_trace(mVcdFile, e_5_fu_519_p2, "e_5_fu_519_p2");
    sc_trace(mVcdFile, e_5_reg_889, "e_5_reg_889");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_146, "ap_sig_bdd_146");
    sc_trace(mVcdFile, exitcond3_fu_513_p2, "exitcond3_fu_513_p2");
    sc_trace(mVcdFile, matrix_addr1_fu_543_p2, "matrix_addr1_fu_543_p2");
    sc_trace(mVcdFile, matrix_addr1_reg_899, "matrix_addr1_reg_899");
    sc_trace(mVcdFile, i_14_fu_558_p2, "i_14_fu_558_p2");
    sc_trace(mVcdFile, i_14_reg_907, "i_14_reg_907");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_162, "ap_sig_bdd_162");
    sc_trace(mVcdFile, exitcond4_fu_552_p2, "exitcond4_fu_552_p2");
    sc_trace(mVcdFile, vector_load_reg_917, "vector_load_reg_917");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_175, "ap_sig_bdd_175");
    sc_trace(mVcdFile, tmp_2_trn_cast_fu_569_p1, "tmp_2_trn_cast_fu_569_p1");
    sc_trace(mVcdFile, tmp_2_trn_cast_reg_921, "tmp_2_trn_cast_reg_921");
    sc_trace(mVcdFile, e_6_fu_579_p2, "e_6_fu_579_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_189, "ap_sig_bdd_189");
    sc_trace(mVcdFile, i_10_fu_613_p2, "i_10_fu_613_p2");
    sc_trace(mVcdFile, i_10_reg_937, "i_10_reg_937");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_201, "ap_sig_bdd_201");
    sc_trace(mVcdFile, exitcond5_fu_607_p2, "exitcond5_fu_607_p2");
    sc_trace(mVcdFile, matrix_addr5_cast_fu_632_p1, "matrix_addr5_cast_fu_632_p1");
    sc_trace(mVcdFile, matrix_addr5_cast_reg_950, "matrix_addr5_cast_reg_950");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_215, "ap_sig_bdd_215");
    sc_trace(mVcdFile, e_7_fu_642_p2, "e_7_fu_642_p2");
    sc_trace(mVcdFile, e_7_reg_958, "e_7_reg_958");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_225, "ap_sig_bdd_225");
    sc_trace(mVcdFile, exitcond8_fu_636_p2, "exitcond8_fu_636_p2");
    sc_trace(mVcdFile, min_4_min_1_fu_668_p3, "min_4_min_1_fu_668_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_239, "ap_sig_bdd_239");
    sc_trace(mVcdFile, i_11_fu_682_p2, "i_11_fu_682_p2");
    sc_trace(mVcdFile, i_11_reg_976, "i_11_reg_976");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_248, "ap_sig_bdd_248");
    sc_trace(mVcdFile, exitcond7_fu_676_p2, "exitcond7_fu_676_p2");
    sc_trace(mVcdFile, vector_load_2_reg_986, "vector_load_2_reg_986");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_261, "ap_sig_bdd_261");
    sc_trace(mVcdFile, matrix_addr3_cast_fu_701_p1, "matrix_addr3_cast_fu_701_p1");
    sc_trace(mVcdFile, matrix_addr3_cast_reg_990, "matrix_addr3_cast_reg_990");
    sc_trace(mVcdFile, e_8_fu_711_p2, "e_8_fu_711_p2");
    sc_trace(mVcdFile, e_8_reg_998, "e_8_reg_998");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_273, "ap_sig_bdd_273");
    sc_trace(mVcdFile, matrix_addr_3_reg_1003, "matrix_addr_3_reg_1003");
    sc_trace(mVcdFile, exitcond10_fu_705_p2, "exitcond10_fu_705_p2");
    sc_trace(mVcdFile, i_12_fu_744_p2, "i_12_fu_744_p2");
    sc_trace(mVcdFile, i_12_reg_1011, "i_12_reg_1011");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_291, "ap_sig_bdd_291");
    sc_trace(mVcdFile, exitcond9_fu_738_p2, "exitcond9_fu_738_p2");
    sc_trace(mVcdFile, vector_load_3_reg_1021, "vector_load_3_reg_1021");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_304, "ap_sig_bdd_304");
    sc_trace(mVcdFile, matrix_addr1_cast_fu_763_p1, "matrix_addr1_cast_fu_763_p1");
    sc_trace(mVcdFile, matrix_addr1_cast_reg_1025, "matrix_addr1_cast_reg_1025");
    sc_trace(mVcdFile, e_9_fu_773_p2, "e_9_fu_773_p2");
    sc_trace(mVcdFile, e_9_reg_1033, "e_9_reg_1033");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_316, "ap_sig_bdd_316");
    sc_trace(mVcdFile, exitcond11_fu_767_p2, "exitcond11_fu_767_p2");
    sc_trace(mVcdFile, tmp_20_reg_1046, "tmp_20_reg_1046");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_334, "ap_sig_bdd_334");
    sc_trace(mVcdFile, i_16_fu_818_p2, "i_16_fu_818_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_bdd_347, "ap_sig_bdd_347");
    sc_trace(mVcdFile, i_17_fu_836_p2, "i_17_fu_836_p2");
    sc_trace(mVcdFile, i_17_reg_1069, "i_17_reg_1069");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st25_fsm_24, "ap_sig_cseq_ST_st25_fsm_24");
    sc_trace(mVcdFile, ap_sig_bdd_359, "ap_sig_bdd_359");
    sc_trace(mVcdFile, tmp_25_fu_842_p1, "tmp_25_fu_842_p1");
    sc_trace(mVcdFile, tmp_25_reg_1074, "tmp_25_reg_1074");
    sc_trace(mVcdFile, exitcond_fu_830_p2, "exitcond_fu_830_p2");
    sc_trace(mVcdFile, i_reg_268, "i_reg_268");
    sc_trace(mVcdFile, exitcond1_fu_460_p2, "exitcond1_fu_460_p2");
    sc_trace(mVcdFile, i_1_reg_279, "i_1_reg_279");
    sc_trace(mVcdFile, e_reg_290, "e_reg_290");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_390, "ap_sig_bdd_390");
    sc_trace(mVcdFile, i_2_reg_301, "i_2_reg_301");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_399, "ap_sig_bdd_399");
    sc_trace(mVcdFile, exitcond6_fu_573_p2, "exitcond6_fu_573_p2");
    sc_trace(mVcdFile, e_1_reg_313, "e_1_reg_313");
    sc_trace(mVcdFile, i_3_reg_324, "i_3_reg_324");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_417, "ap_sig_bdd_417");
    sc_trace(mVcdFile, min_reg_336, "min_reg_336");
    sc_trace(mVcdFile, e_2_reg_348, "e_2_reg_348");
    sc_trace(mVcdFile, min_1_reg_359, "min_1_reg_359");
    sc_trace(mVcdFile, min_3_reg_370, "min_3_reg_370");
    sc_trace(mVcdFile, i_4_reg_383, "i_4_reg_383");
    sc_trace(mVcdFile, e_3_reg_395, "e_3_reg_395");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_447, "ap_sig_bdd_447");
    sc_trace(mVcdFile, i_5_reg_406, "i_5_reg_406");
    sc_trace(mVcdFile, e_4_reg_419, "e_4_reg_419");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_bdd_463, "ap_sig_bdd_463");
    sc_trace(mVcdFile, i_6_reg_431, "i_6_reg_431");
    sc_trace(mVcdFile, i_7_reg_443, "i_7_reg_443");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st26_fsm_25, "ap_sig_cseq_ST_st26_fsm_25");
    sc_trace(mVcdFile, ap_sig_bdd_477, "ap_sig_bdd_477");
    sc_trace(mVcdFile, tmp_22_fu_824_p2, "tmp_22_fu_824_p2");
    sc_trace(mVcdFile, tmp_fu_455_p1, "tmp_fu_455_p1");
    sc_trace(mVcdFile, tmp_1_fu_472_p1, "tmp_1_fu_472_p1");
    sc_trace(mVcdFile, tmp_9_fu_534_p1, "tmp_9_fu_534_p1");
    sc_trace(mVcdFile, tmp_15_fu_548_p1, "tmp_15_fu_548_p1");
    sc_trace(mVcdFile, tmp_2_fu_564_p1, "tmp_2_fu_564_p1");
    sc_trace(mVcdFile, tmp_28_fu_602_p1, "tmp_28_fu_602_p1");
    sc_trace(mVcdFile, tmp_10_fu_619_p1, "tmp_10_fu_619_p1");
    sc_trace(mVcdFile, tmp_30_fu_657_p1, "tmp_30_fu_657_p1");
    sc_trace(mVcdFile, tmp_13_fu_688_p1, "tmp_13_fu_688_p1");
    sc_trace(mVcdFile, tmp_31_fu_726_p1, "tmp_31_fu_726_p1");
    sc_trace(mVcdFile, tmp_17_fu_750_p1, "tmp_17_fu_750_p1");
    sc_trace(mVcdFile, tmp_32_fu_788_p1, "tmp_32_fu_788_p1");
    sc_trace(mVcdFile, tmp_23_fu_793_p1, "tmp_23_fu_793_p1");
    sc_trace(mVcdFile, tmp_24_fu_799_p2, "tmp_24_fu_799_p2");
    sc_trace(mVcdFile, tmp_21_fu_813_p1, "tmp_21_fu_813_p1");
    sc_trace(mVcdFile, tmp_19_fu_731_p2, "tmp_19_fu_731_p2");
    sc_trace(mVcdFile, tmp_5_fu_489_p1, "tmp_5_fu_489_p1");
    sc_trace(mVcdFile, tmp_12_fu_501_p3, "tmp_12_fu_501_p3");
    sc_trace(mVcdFile, tmp_7_cast_fu_525_p1, "tmp_7_cast_fu_525_p1");
    sc_trace(mVcdFile, tmp_8_fu_529_p2, "tmp_8_fu_529_p2");
    sc_trace(mVcdFile, tmp_trn_cast_fu_539_p1, "tmp_trn_cast_fu_539_p1");
    sc_trace(mVcdFile, tmp_27_fu_585_p3, "tmp_27_fu_585_p3");
    sc_trace(mVcdFile, matrix_addr7_cast_fu_593_p1, "matrix_addr7_cast_fu_593_p1");
    sc_trace(mVcdFile, matrix_addr8_fu_597_p2, "matrix_addr8_fu_597_p2");
    sc_trace(mVcdFile, tmp_18_fu_624_p3, "tmp_18_fu_624_p3");
    sc_trace(mVcdFile, tmp_15_trn_cast_fu_648_p1, "tmp_15_trn_cast_fu_648_p1");
    sc_trace(mVcdFile, matrix_addr6_fu_652_p2, "matrix_addr6_fu_652_p2");
    sc_trace(mVcdFile, tmp_14_fu_662_p2, "tmp_14_fu_662_p2");
    sc_trace(mVcdFile, tmp_26_fu_693_p3, "tmp_26_fu_693_p3");
    sc_trace(mVcdFile, tmp_20_trn_cast_fu_717_p1, "tmp_20_trn_cast_fu_717_p1");
    sc_trace(mVcdFile, matrix_addr4_fu_721_p2, "matrix_addr4_fu_721_p2");
    sc_trace(mVcdFile, tmp_29_fu_755_p3, "tmp_29_fu_755_p3");
    sc_trace(mVcdFile, tmp_24_trn_cast_fu_779_p1, "tmp_24_trn_cast_fu_779_p1");
    sc_trace(mVcdFile, matrix_addr2_fu_783_p2, "matrix_addr2_fu_783_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dijkstra.hdltvin.dat");
    mHdltvoutHandle.open("dijkstra.hdltvout.dat");
}

dijkstra::~dijkstra() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete vector_U;
    delete matrix_U;
    delete result_U;
}

void dijkstra::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0))) {
        e_1_reg_313 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_reg_917.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_573_p2.read()))) {
        e_1_reg_313 = e_6_fu_579_p2.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        e_2_reg_348 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        e_2_reg_348 = e_7_reg_958.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        e_3_reg_395 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        e_3_reg_395 = e_8_reg_998.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        e_4_reg_419 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        e_4_reg_419 = e_9_reg_1033.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        e_reg_290 = e_5_reg_889.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_477_p2.read(), ap_const_lv1_0))) {
        e_reg_290 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_460_p2.read()))) {
        i_1_reg_279 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_513_p2.read()))) {
        i_1_reg_279 = i_9_reg_871.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_reg_917.read()) || 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_573_p2.read())))) {
        i_2_reg_301 = i_14_reg_907.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        i_2_reg_301 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_552_p2.read()))) {
        i_3_reg_324 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        i_3_reg_324 = i_10_reg_937.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_607_p2.read()))) {
        i_4_reg_383 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_2_reg_986.read()) || 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond10_fu_705_p2.read())))) {
        i_4_reg_383 = i_11_reg_976.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_676_p2.read()))) {
        i_5_reg_406 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_3_reg_1021.read()) || 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond11_fu_767_p2.read())))) {
        i_5_reg_406 = i_12_reg_1011.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_738_p2.read()))) {
        i_6_reg_431 = ap_const_lv4_1;
    } else if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_20_reg_1046.read()))) {
        i_6_reg_431 = i_16_fu_818_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && 
         ((!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read()) && 
           !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_20_reg_1046.read())) || 
          (esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
           !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read()))))) {
        i_7_reg_443 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read())) {
        i_7_reg_443 = i_17_reg_1069.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_460_p2.read()))) {
        i_reg_268 = i_8_fu_466_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_268 = ap_const_lv4_0;
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        min_1_reg_359 = min_reg_336.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        min_1_reg_359 = min_4_min_1_fu_668_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_636_p2.read()))) {
        min_3_reg_370 = min_1_reg_359.read();
    } else if ((esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        min_3_reg_370 = min_reg_336.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_552_p2.read()))) {
        min_reg_336 = ap_const_lv8_FF;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        min_reg_336 = min_3_reg_370.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        e_5_reg_889 = e_5_fu_519_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        e_7_reg_958 = e_7_fu_642_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_2_reg_986.read()))) {
        e_8_reg_998 = e_8_fu_711_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_3_reg_1021.read()))) {
        e_9_reg_1033 = e_9_fu_773_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        i_10_reg_937 = i_10_fu_613_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        i_11_reg_976 = i_11_fu_682_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        i_12_reg_1011 = i_12_fu_744_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        i_14_reg_907 = i_14_fu_558_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        i_17_reg_1069 = i_17_fu_836_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_9_reg_871 = i_9_fu_483_p2.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        matrix_addr1_cast_reg_1025 = matrix_addr1_cast_fu_763_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_513_p2.read()))) {
        matrix_addr1_reg_899 = matrix_addr1_fu_543_p2.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        matrix_addr3_cast_reg_990 = matrix_addr3_cast_fu_701_p1.read();
    }
    if ((!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        matrix_addr5_cast_reg_950 = matrix_addr5_cast_fu_632_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond2_fu_477_p2.read(), ap_const_lv1_0))) {
        matrix_addr9_cast_reg_881 = matrix_addr9_cast_fu_509_p1.read();
        tmp_4_reg_876 = tmp_4_fu_493_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_2_reg_986.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond10_fu_705_p2.read()))) {
        matrix_addr_3_reg_1003 =  (sc_lv<6>) (tmp_31_fu_726_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        tmp_20_reg_1046 = i_6_reg_431.read().range(3, 3);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_830_p2.read()))) {
        tmp_25_reg_1074 = tmp_25_fu_842_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && !esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0))) {
        tmp_2_trn_cast_reg_921 = tmp_2_trn_cast_fu_569_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        vector_load_2_reg_986 = vector_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        vector_load_3_reg_1021 = vector_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        vector_load_reg_917 = vector_q0.read();
    }
}

void dijkstra::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_830_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_830_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_bdd_120() {
    ap_sig_bdd_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dijkstra::thread_ap_sig_bdd_129() {
    ap_sig_bdd_129 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dijkstra::thread_ap_sig_bdd_146() {
    ap_sig_bdd_146 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dijkstra::thread_ap_sig_bdd_162() {
    ap_sig_bdd_162 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dijkstra::thread_ap_sig_bdd_175() {
    ap_sig_bdd_175 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dijkstra::thread_ap_sig_bdd_189() {
    ap_sig_bdd_189 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dijkstra::thread_ap_sig_bdd_201() {
    ap_sig_bdd_201 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dijkstra::thread_ap_sig_bdd_215() {
    ap_sig_bdd_215 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dijkstra::thread_ap_sig_bdd_225() {
    ap_sig_bdd_225 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dijkstra::thread_ap_sig_bdd_239() {
    ap_sig_bdd_239 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dijkstra::thread_ap_sig_bdd_248() {
    ap_sig_bdd_248 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void dijkstra::thread_ap_sig_bdd_261() {
    ap_sig_bdd_261 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void dijkstra::thread_ap_sig_bdd_273() {
    ap_sig_bdd_273 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void dijkstra::thread_ap_sig_bdd_291() {
    ap_sig_bdd_291 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void dijkstra::thread_ap_sig_bdd_304() {
    ap_sig_bdd_304 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void dijkstra::thread_ap_sig_bdd_316() {
    ap_sig_bdd_316 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void dijkstra::thread_ap_sig_bdd_334() {
    ap_sig_bdd_334 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void dijkstra::thread_ap_sig_bdd_347() {
    ap_sig_bdd_347 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void dijkstra::thread_ap_sig_bdd_359() {
    ap_sig_bdd_359 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(24, 24));
}

void dijkstra::thread_ap_sig_bdd_390() {
    ap_sig_bdd_390 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dijkstra::thread_ap_sig_bdd_399() {
    ap_sig_bdd_399 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dijkstra::thread_ap_sig_bdd_417() {
    ap_sig_bdd_417 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dijkstra::thread_ap_sig_bdd_42() {
    ap_sig_bdd_42 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dijkstra::thread_ap_sig_bdd_447() {
    ap_sig_bdd_447 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void dijkstra::thread_ap_sig_bdd_463() {
    ap_sig_bdd_463 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void dijkstra::thread_ap_sig_bdd_477() {
    ap_sig_bdd_477 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(25, 25));
}

void dijkstra::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_201.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_215.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_225.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_239.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_417.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_248.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_261.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_273.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_447.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_291.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_42.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_304.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_316.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_bdd_463.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_334.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_bdd_347.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st25_fsm_24() {
    if (ap_sig_bdd_359.read()) {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st26_fsm_25() {
    if (ap_sig_bdd_477.read()) {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_120.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_129.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_146.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_390.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_399.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_162.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_175.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_189.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dijkstra::thread_e_5_fu_519_p2() {
    e_5_fu_519_p2 = (!e_reg_290.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(e_reg_290.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_e_6_fu_579_p2() {
    e_6_fu_579_p2 = (!e_1_reg_313.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(e_1_reg_313.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_e_7_fu_642_p2() {
    e_7_fu_642_p2 = (!e_2_reg_348.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(e_2_reg_348.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_e_8_fu_711_p2() {
    e_8_fu_711_p2 = (!e_3_reg_395.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(e_3_reg_395.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_e_9_fu_773_p2() {
    e_9_fu_773_p2 = (!e_4_reg_419.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(e_4_reg_419.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_exitcond10_fu_705_p2() {
    exitcond10_fu_705_p2 = (!e_3_reg_395.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(e_3_reg_395.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond11_fu_767_p2() {
    exitcond11_fu_767_p2 = (!e_4_reg_419.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(e_4_reg_419.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond1_fu_460_p2() {
    exitcond1_fu_460_p2 = (!i_reg_268.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_268.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond2_fu_477_p2() {
    exitcond2_fu_477_p2 = (!i_1_reg_279.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_279.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond3_fu_513_p2() {
    exitcond3_fu_513_p2 = (!e_reg_290.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(e_reg_290.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond4_fu_552_p2() {
    exitcond4_fu_552_p2 = (!i_2_reg_301.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_301.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond5_fu_607_p2() {
    exitcond5_fu_607_p2 = (!i_3_reg_324.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_3_reg_324.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond6_fu_573_p2() {
    exitcond6_fu_573_p2 = (!e_1_reg_313.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(e_1_reg_313.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond7_fu_676_p2() {
    exitcond7_fu_676_p2 = (!i_4_reg_383.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_4_reg_383.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond8_fu_636_p2() {
    exitcond8_fu_636_p2 = (!e_2_reg_348.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(e_2_reg_348.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond9_fu_738_p2() {
    exitcond9_fu_738_p2 = (!i_5_reg_406.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_5_reg_406.read() == ap_const_lv4_8);
}

void dijkstra::thread_exitcond_fu_830_p2() {
    exitcond_fu_830_p2 = (!i_7_reg_443.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_7_reg_443.read() == ap_const_lv4_8);
}

void dijkstra::thread_i_10_fu_613_p2() {
    i_10_fu_613_p2 = (!i_3_reg_324.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_3_reg_324.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_11_fu_682_p2() {
    i_11_fu_682_p2 = (!i_4_reg_383.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_4_reg_383.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_12_fu_744_p2() {
    i_12_fu_744_p2 = (!i_5_reg_406.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_5_reg_406.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_14_fu_558_p2() {
    i_14_fu_558_p2 = (!i_2_reg_301.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_2_reg_301.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_16_fu_818_p2() {
    i_16_fu_818_p2 = (!i_6_reg_431.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_6_reg_431.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_17_fu_836_p2() {
    i_17_fu_836_p2 = (!i_7_reg_443.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_7_reg_443.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_8_fu_466_p2() {
    i_8_fu_466_p2 = (!i_reg_268.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_268.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_i_9_fu_483_p2() {
    i_9_fu_483_p2 = (!i_1_reg_279.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_1_reg_279.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dijkstra::thread_in_data_V_address0() {
    in_data_V_address0 =  (sc_lv<6>) (tmp_9_fu_534_p1.read());
}

void dijkstra::thread_in_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        in_data_V_ce0 = ap_const_logic_1;
    } else {
        in_data_V_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_in_last_V_address0() {
    in_last_V_address0 = ap_const_lv6_0;
}

void dijkstra::thread_in_last_V_address1() {
    in_last_V_address1 = ap_const_lv6_0;
}

void dijkstra::thread_in_last_V_ce0() {
    in_last_V_ce0 = ap_const_logic_0;
}

void dijkstra::thread_in_last_V_ce1() {
    in_last_V_ce1 = ap_const_logic_0;
}

void dijkstra::thread_in_last_V_d0() {
    in_last_V_d0 = ap_const_lv1_0;
}

void dijkstra::thread_in_last_V_d1() {
    in_last_V_d1 = ap_const_lv1_0;
}

void dijkstra::thread_in_last_V_we0() {
    in_last_V_we0 = ap_const_logic_0;
}

void dijkstra::thread_in_last_V_we1() {
    in_last_V_we1 = ap_const_logic_0;
}

void dijkstra::thread_matrix_addr1_cast_fu_763_p1() {
    matrix_addr1_cast_fu_763_p1 = esl_zext<8,7>(tmp_29_fu_755_p3.read());
}

void dijkstra::thread_matrix_addr1_fu_543_p2() {
    matrix_addr1_fu_543_p2 = (!matrix_addr9_cast_reg_881.read().is_01() || !tmp_trn_cast_fu_539_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_addr9_cast_reg_881.read()) + sc_biguint<8>(tmp_trn_cast_fu_539_p1.read()));
}

void dijkstra::thread_matrix_addr2_fu_783_p2() {
    matrix_addr2_fu_783_p2 = (!matrix_addr1_cast_reg_1025.read().is_01() || !tmp_24_trn_cast_fu_779_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_addr1_cast_reg_1025.read()) + sc_biguint<8>(tmp_24_trn_cast_fu_779_p1.read()));
}

void dijkstra::thread_matrix_addr3_cast_fu_701_p1() {
    matrix_addr3_cast_fu_701_p1 = esl_zext<8,7>(tmp_26_fu_693_p3.read());
}

void dijkstra::thread_matrix_addr4_fu_721_p2() {
    matrix_addr4_fu_721_p2 = (!matrix_addr3_cast_reg_990.read().is_01() || !tmp_20_trn_cast_fu_717_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_addr3_cast_reg_990.read()) + sc_biguint<8>(tmp_20_trn_cast_fu_717_p1.read()));
}

void dijkstra::thread_matrix_addr5_cast_fu_632_p1() {
    matrix_addr5_cast_fu_632_p1 = esl_zext<8,7>(tmp_18_fu_624_p3.read());
}

void dijkstra::thread_matrix_addr6_fu_652_p2() {
    matrix_addr6_fu_652_p2 = (!matrix_addr5_cast_reg_950.read().is_01() || !tmp_15_trn_cast_fu_648_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_addr5_cast_reg_950.read()) + sc_biguint<8>(tmp_15_trn_cast_fu_648_p1.read()));
}

void dijkstra::thread_matrix_addr7_cast_fu_593_p1() {
    matrix_addr7_cast_fu_593_p1 = esl_zext<8,7>(tmp_27_fu_585_p3.read());
}

void dijkstra::thread_matrix_addr8_fu_597_p2() {
    matrix_addr8_fu_597_p2 = (!matrix_addr7_cast_fu_593_p1.read().is_01() || !tmp_2_trn_cast_reg_921.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_addr7_cast_fu_593_p1.read()) + sc_biguint<8>(tmp_2_trn_cast_reg_921.read()));
}

void dijkstra::thread_matrix_addr9_cast_fu_509_p1() {
    matrix_addr9_cast_fu_509_p1 = esl_zext<8,7>(tmp_12_fu_501_p3.read());
}

void dijkstra::thread_matrix_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        matrix_address0 = matrix_addr_3_reg_1003.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        matrix_address0 =  (sc_lv<6>) (tmp_28_fu_602_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        matrix_address0 =  (sc_lv<6>) (tmp_15_fu_548_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        matrix_address0 =  (sc_lv<6>) (tmp_32_fu_788_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        matrix_address0 =  (sc_lv<6>) (tmp_31_fu_726_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        matrix_address0 =  (sc_lv<6>) (tmp_30_fu_657_p1.read());
    } else {
        matrix_address0 = "XXXXXX";
    }
}

void dijkstra::thread_matrix_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        matrix_ce0 = ap_const_logic_1;
    } else {
        matrix_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_matrix_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        matrix_d0 = tmp_19_fu_731_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        matrix_d0 = ap_const_lv8_FF;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        matrix_d0 = in_data_V_q0.read();
    } else {
        matrix_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dijkstra::thread_matrix_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_reg_917.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_573_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        matrix_we0 = ap_const_logic_1;
    } else {
        matrix_we0 = ap_const_logic_0;
    }
}

void dijkstra::thread_min_4_min_1_fu_668_p3() {
    min_4_min_1_fu_668_p3 = (!tmp_14_fu_662_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_14_fu_662_p2.read()[0].to_bool())? matrix_q0.read(): min_1_reg_359.read());
}

void dijkstra::thread_out_data_V_address0() {
    out_data_V_address0 =  (sc_lv<3>) (tmp_25_reg_1074.read());
}

void dijkstra::thread_out_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read())) {
        out_data_V_ce0 = ap_const_logic_1;
    } else {
        out_data_V_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_out_data_V_d0() {
    out_data_V_d0 = esl_zext<8,4>(result_q0.read());
}

void dijkstra::thread_out_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read()))) {
        out_data_V_we0 = ap_const_logic_1;
    } else {
        out_data_V_we0 = ap_const_logic_0;
    }
}

void dijkstra::thread_out_last_V_address0() {
    out_last_V_address0 =  (sc_lv<3>) (tmp_25_fu_842_p1.read());
}

void dijkstra::thread_out_last_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        out_last_V_ce0 = ap_const_logic_1;
    } else {
        out_last_V_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_out_last_V_d0() {
    out_last_V_d0 = (!i_7_reg_443.read().is_01() || !ap_const_lv4_6.is_01())? sc_lv<1>(): (sc_biguint<4>(i_7_reg_443.read()) > sc_biguint<4>(ap_const_lv4_6));
}

void dijkstra::thread_out_last_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_830_p2.read())))) {
        out_last_V_we0 = ap_const_logic_1;
    } else {
        out_last_V_we0 = ap_const_logic_0;
    }
}

void dijkstra::thread_result_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        result_address0 =  (sc_lv<3>) (tmp_23_fu_793_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        result_address0 =  (sc_lv<3>) (tmp_25_fu_842_p1.read());
    } else {
        result_address0 =  (sc_lv<3>) ("XXX");
    }
}

void dijkstra::thread_result_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        result_ce0 = ap_const_logic_1;
    } else {
        result_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_result_d0() {
    result_d0 = i_5_reg_406.read();
}

void dijkstra::thread_result_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_799_p2.read())))) {
        result_we0 = ap_const_logic_1;
    } else {
        result_we0 = ap_const_logic_0;
    }
}

void dijkstra::thread_tmp_10_fu_619_p1() {
    tmp_10_fu_619_p1 = esl_zext<64,4>(i_3_reg_324.read());
}

void dijkstra::thread_tmp_12_fu_501_p3() {
    tmp_12_fu_501_p3 = esl_concat<4,3>(i_1_reg_279.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_13_fu_688_p1() {
    tmp_13_fu_688_p1 = esl_zext<64,4>(i_4_reg_383.read());
}

void dijkstra::thread_tmp_14_fu_662_p2() {
    tmp_14_fu_662_p2 = (!matrix_q0.read().is_01() || !min_1_reg_359.read().is_01())? sc_lv<1>(): (sc_biguint<8>(matrix_q0.read()) < sc_biguint<8>(min_1_reg_359.read()));
}

void dijkstra::thread_tmp_15_fu_548_p1() {
    tmp_15_fu_548_p1 = esl_zext<64,8>(matrix_addr1_reg_899.read());
}

void dijkstra::thread_tmp_15_trn_cast_fu_648_p1() {
    tmp_15_trn_cast_fu_648_p1 = esl_zext<8,4>(e_2_reg_348.read());
}

void dijkstra::thread_tmp_17_fu_750_p1() {
    tmp_17_fu_750_p1 = esl_zext<64,4>(i_5_reg_406.read());
}

void dijkstra::thread_tmp_18_fu_624_p3() {
    tmp_18_fu_624_p3 = esl_concat<4,3>(i_3_reg_324.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_19_fu_731_p2() {
    tmp_19_fu_731_p2 = (!matrix_q0.read().is_01() || !min_reg_336.read().is_01())? sc_lv<8>(): (sc_biguint<8>(matrix_q0.read()) - sc_biguint<8>(min_reg_336.read()));
}

void dijkstra::thread_tmp_1_fu_472_p1() {
    tmp_1_fu_472_p1 = esl_zext<64,4>(i_reg_268.read());
}

void dijkstra::thread_tmp_20_trn_cast_fu_717_p1() {
    tmp_20_trn_cast_fu_717_p1 = esl_zext<8,4>(e_3_reg_395.read());
}

void dijkstra::thread_tmp_21_fu_813_p1() {
    tmp_21_fu_813_p1 = esl_zext<64,4>(i_6_reg_431.read());
}

void dijkstra::thread_tmp_22_fu_824_p2() {
    tmp_22_fu_824_p2 = (!i_6_reg_431.read().is_01() || !ap_const_lv4_6.is_01())? sc_lv<1>(): (sc_biguint<4>(i_6_reg_431.read()) > sc_biguint<4>(ap_const_lv4_6));
}

void dijkstra::thread_tmp_23_fu_793_p1() {
    tmp_23_fu_793_p1 = esl_zext<64,4>(e_4_reg_419.read());
}

void dijkstra::thread_tmp_24_fu_799_p2() {
    tmp_24_fu_799_p2 = (!matrix_q0.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(matrix_q0.read() == ap_const_lv8_0);
}

void dijkstra::thread_tmp_24_trn_cast_fu_779_p1() {
    tmp_24_trn_cast_fu_779_p1 = esl_zext<8,4>(e_4_reg_419.read());
}

void dijkstra::thread_tmp_25_fu_842_p1() {
    tmp_25_fu_842_p1 = esl_zext<64,4>(i_7_reg_443.read());
}

void dijkstra::thread_tmp_26_fu_693_p3() {
    tmp_26_fu_693_p3 = esl_concat<4,3>(i_4_reg_383.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_27_fu_585_p3() {
    tmp_27_fu_585_p3 = esl_concat<4,3>(e_1_reg_313.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_28_fu_602_p1() {
    tmp_28_fu_602_p1 = esl_zext<64,8>(matrix_addr8_fu_597_p2.read());
}

void dijkstra::thread_tmp_29_fu_755_p3() {
    tmp_29_fu_755_p3 = esl_concat<4,3>(i_5_reg_406.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_2_fu_564_p1() {
    tmp_2_fu_564_p1 = esl_zext<64,4>(i_2_reg_301.read());
}

void dijkstra::thread_tmp_2_trn_cast_fu_569_p1() {
    tmp_2_trn_cast_fu_569_p1 = esl_zext<8,4>(i_2_reg_301.read());
}

void dijkstra::thread_tmp_30_fu_657_p1() {
    tmp_30_fu_657_p1 = esl_zext<64,8>(matrix_addr6_fu_652_p2.read());
}

void dijkstra::thread_tmp_31_fu_726_p1() {
    tmp_31_fu_726_p1 = esl_zext<64,8>(matrix_addr4_fu_721_p2.read());
}

void dijkstra::thread_tmp_32_fu_788_p1() {
    tmp_32_fu_788_p1 = esl_zext<64,8>(matrix_addr2_fu_783_p2.read());
}

void dijkstra::thread_tmp_4_fu_493_p3() {
    tmp_4_fu_493_p3 = esl_concat<3,3>(tmp_5_fu_489_p1.read(), ap_const_lv3_0);
}

void dijkstra::thread_tmp_5_fu_489_p1() {
    tmp_5_fu_489_p1 = i_1_reg_279.read().range(3-1, 0);
}

void dijkstra::thread_tmp_7_cast_fu_525_p1() {
    tmp_7_cast_fu_525_p1 = esl_zext<6,4>(e_reg_290.read());
}

void dijkstra::thread_tmp_8_fu_529_p2() {
    tmp_8_fu_529_p2 = (!tmp_4_reg_876.read().is_01() || !tmp_7_cast_fu_525_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_4_reg_876.read()) + sc_biguint<6>(tmp_7_cast_fu_525_p1.read()));
}

void dijkstra::thread_tmp_9_fu_534_p1() {
    tmp_9_fu_534_p1 = esl_zext<64,6>(tmp_8_fu_529_p2.read());
}

void dijkstra::thread_tmp_fu_455_p1() {
    tmp_fu_455_p1 = esl_zext<64,8>(start_point_V.read());
}

void dijkstra::thread_tmp_trn_cast_fu_539_p1() {
    tmp_trn_cast_fu_539_p1 = esl_zext<8,4>(e_reg_290.read());
}

void dijkstra::thread_vector_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_23_fu_793_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_1_fu_472_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_fu_455_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_21_fu_813_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_17_fu_750_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_13_fu_688_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_10_fu_619_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        vector_address0 =  (sc_lv<3>) (tmp_2_fu_564_p1.read());
    } else {
        vector_address0 =  (sc_lv<3>) ("XXX");
    }
}

void dijkstra::thread_vector_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        vector_ce0 = ap_const_logic_1;
    } else {
        vector_ce0 = ap_const_logic_0;
    }
}

void dijkstra::thread_vector_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        vector_d0 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        vector_d0 = ap_const_lv1_1;
    } else {
        vector_d0 =  (sc_lv<1>) ("X");
    }
}

void dijkstra::thread_vector_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_460_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_799_p2.read())))) {
        vector_we0 = ap_const_logic_1;
    } else {
        vector_we0 = ap_const_logic_0;
    }
}

void dijkstra::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_460_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(exitcond2_fu_477_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_513_p2.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_552_p2.read())) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_reg_917.read()) || !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_573_p2.read()))) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_607_p2.read())) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_13;
            }
            break;
        case 2048 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_636_p2.read())) {
                ap_NS_fsm = ap_ST_st14_fsm_13;
            } else {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_676_p2.read())) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_2_reg_986.read()) || !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond10_fu_705_p2.read()))) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else {
                ap_NS_fsm = ap_ST_st18_fsm_17;
            }
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 262144 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_738_p2.read())) {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, vector_load_3_reg_1021.read()) || !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond11_fu_767_p2.read()))) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st22_fsm_21;
            }
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 8388608 : 
            if (((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_20_reg_1046.read())) || (esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read())))) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else if (((!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_20_reg_1046.read())) || (esl_seteq<1,1,1>(vector_q0.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_824_p2.read())))) {
                ap_NS_fsm = ap_ST_st25_fsm_24;
            } else {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            }
            break;
        case 16777216 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_830_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st26_fsm_25;
            }
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<26>) ("XXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void dijkstra::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_data_V_address0\" :  \"" << in_data_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_data_V_ce0\" :  \"" << in_data_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_data_V_q0\" :  \"" << in_data_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_address0\" :  \"" << in_last_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_ce0\" :  \"" << in_last_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_we0\" :  \"" << in_last_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_d0\" :  \"" << in_last_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_last_V_q0\" :  \"" << in_last_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_address1\" :  \"" << in_last_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_ce1\" :  \"" << in_last_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_we1\" :  \"" << in_last_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_last_V_d1\" :  \"" << in_last_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_last_V_q1\" :  \"" << in_last_V_q1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"start_point_V\" :  \"" << start_point_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V_address0\" :  \"" << out_data_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V_ce0\" :  \"" << out_data_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V_we0\" :  \"" << out_data_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V_d0\" :  \"" << out_data_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_last_V_address0\" :  \"" << out_last_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_last_V_ce0\" :  \"" << out_last_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_last_V_we0\" :  \"" << out_last_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_last_V_d0\" :  \"" << out_last_V_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

