#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in_data_V_address0", 6, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("in_data_V_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("in_data_V_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("in_last_V_address0", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("in_last_V_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("in_last_V_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("in_last_V_d0", 1, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("in_last_V_q0", 1, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("in_last_V_address1", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("in_last_V_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("in_last_V_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("in_last_V_d1", 1, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("in_last_V_q1", 1, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("start_point_V", 8, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("out_data_V_address0", 3, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("out_data_V_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("out_data_V_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("out_data_V_d0", 8, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("out_last_V_address0", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("out_last_V_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("out_last_V_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("out_last_V_d0", 1, hls_out, 4, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "dijkstra";
