// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XDIJKSTRA_H
#define XDIJKSTRA_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdijkstra_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XDijkstra_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XDijkstra;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDijkstra_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDijkstra_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDijkstra_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDijkstra_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDijkstra_Initialize(XDijkstra *InstancePtr, u16 DeviceId);
XDijkstra_Config* XDijkstra_LookupConfig(u16 DeviceId);
int XDijkstra_CfgInitialize(XDijkstra *InstancePtr, XDijkstra_Config *ConfigPtr);
#else
int XDijkstra_Initialize(XDijkstra *InstancePtr, const char* InstanceName);
int XDijkstra_Release(XDijkstra *InstancePtr);
#endif

void XDijkstra_Start(XDijkstra *InstancePtr);
u32 XDijkstra_IsDone(XDijkstra *InstancePtr);
u32 XDijkstra_IsIdle(XDijkstra *InstancePtr);
u32 XDijkstra_IsReady(XDijkstra *InstancePtr);
void XDijkstra_EnableAutoRestart(XDijkstra *InstancePtr);
void XDijkstra_DisableAutoRestart(XDijkstra *InstancePtr);

void XDijkstra_Set_start_point_V(XDijkstra *InstancePtr, u32 Data);
u32 XDijkstra_Get_start_point_V(XDijkstra *InstancePtr);

void XDijkstra_InterruptGlobalEnable(XDijkstra *InstancePtr);
void XDijkstra_InterruptGlobalDisable(XDijkstra *InstancePtr);
void XDijkstra_InterruptEnable(XDijkstra *InstancePtr, u32 Mask);
void XDijkstra_InterruptDisable(XDijkstra *InstancePtr, u32 Mask);
void XDijkstra_InterruptClear(XDijkstra *InstancePtr, u32 Mask);
u32 XDijkstra_InterruptGetEnabled(XDijkstra *InstancePtr);
u32 XDijkstra_InterruptGetStatus(XDijkstra *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
