// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdijkstra.h"

extern XDijkstra_Config XDijkstra_ConfigTable[];

XDijkstra_Config *XDijkstra_LookupConfig(u16 DeviceId) {
	XDijkstra_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDIJKSTRA_NUM_INSTANCES; Index++) {
		if (XDijkstra_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDijkstra_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDijkstra_Initialize(XDijkstra *InstancePtr, u16 DeviceId) {
	XDijkstra_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDijkstra_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDijkstra_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

