// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdijkstra.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDijkstra_CfgInitialize(XDijkstra *InstancePtr, XDijkstra_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDijkstra_Start(XDijkstra *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL) & 0x80;
    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDijkstra_IsDone(XDijkstra *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDijkstra_IsIdle(XDijkstra *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDijkstra_IsReady(XDijkstra *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDijkstra_EnableAutoRestart(XDijkstra *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XDijkstra_DisableAutoRestart(XDijkstra *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_AP_CTRL, 0);
}

void XDijkstra_Set_start_point_V(XDijkstra *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_START_POINT_V_DATA, Data);
}

u32 XDijkstra_Get_start_point_V(XDijkstra *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_START_POINT_V_DATA);
    return Data;
}

void XDijkstra_InterruptGlobalEnable(XDijkstra *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_GIE, 1);
}

void XDijkstra_InterruptGlobalDisable(XDijkstra *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_GIE, 0);
}

void XDijkstra_InterruptEnable(XDijkstra *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_IER);
    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_IER, Register | Mask);
}

void XDijkstra_InterruptDisable(XDijkstra *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_IER);
    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_IER, Register & (~Mask));
}

void XDijkstra_InterruptClear(XDijkstra *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDijkstra_WriteReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_ISR, Mask);
}

u32 XDijkstra_InterruptGetEnabled(XDijkstra *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_IER);
}

u32 XDijkstra_InterruptGetStatus(XDijkstra *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDijkstra_ReadReg(InstancePtr->Axilites_BaseAddress, XDIJKSTRA_AXILITES_ADDR_ISR);
}

